export type Product = {
  id: string;
  name: string;
  price: number;
  brand: string;
  category: string;
  image: string;
  stock: number;
  description: string;
};

export const CATEGORIES = [
  "Chargers",
  "Data Cables",
  "Power Banks",
  "Earbuds",
  "Headphones",
  "Smart Watches",
  "Phone Cases",
  "Screen Protection",
  "Car Accessories",
  "Audio",
  "Storage",
  "Ronin Products",
  "Apple Products",
  "Accessories",
] as const;

export const SEED_PRODUCTS: Product[] = [
  // ====== Earbuds ======
  {
    id: "air-buds",
    name: "Air Buds",
    price: 2000,
    brand: "Generic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/apple-copy-earbuds-lightning.jpg",
    stock: 30,
    description: "Affordable wireless earbuds with comfortable fit and decent sound quality.",
  },
  {
    id: "anker-soundcore-r50i",
    name: "Anker Soundcore R50i Wireless Earbuds",
    price: 3000,
    brand: "Anker",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/anker-soundcore-r50i.jpg",
    stock: 20,
    description: "Anker Soundcore R50i earbuds with rich bass and long battery life.",
  },
  {
    id: "apple-airpods-4",
    name: "Apple AirPods 4",
    price: 6500,
    brand: "Apple",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/airpods-4.jpg",
    stock: 15,
    description: "Apple AirPods 4 with seamless connectivity and premium sound.",
  },
  {
    id: "apple-airpods-max-2",
    name: "Apple AirPods Max 2 (A+)",
    price: 2000,
    brand: "Apple",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/airpods-max-2_9f50ba80-7dc8-4e27-a434-39ede268daa4.jpg",
    stock: 18,
    description: "Premium replica AirPods Max 2 with immersive over-ear sound.",
  },
  {
    id: "apple-airpods-pro-3",
    name: "Apple AirPods Pro 3 (Master)",
    price: 7500,
    brand: "Apple",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/airpods-pro-3.jpg",
    stock: 12,
    description: "Apple AirPods Pro 3 with active noise cancellation and adaptive audio.",
  },
  {
    id: "apple-earpods-3-5mm",
    name: "Apple EarPods with 3.5mm Headphone Plug",
    price: 500,
    brand: "Apple",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/apple-lightning-to-3-5mm-adapter.jpg",
    stock: 35,
    description: "Wired Apple EarPods with 3.5mm jack for universal compatibility.",
  },
  {
    id: "apple-earpods-lightning",
    name: "Apple EarPods with Lightning Connector",
    price: 600,
    brand: "Apple",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/apple-earpods-lightning.jpg",
    stock: 30,
    description: "Apple EarPods with Lightning connector for iPhone and iPad.",
  },
  {
    id: "apple-earpods-usb-c",
    name: "Apple EarPods with USB-C Connector",
    price: 850,
    brand: "Apple",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/apple-earpods-usbc.png",
    stock: 25,
    description: "Apple EarPods with USB-C for modern Mac and iPad devices.",
  },
  {
    id: "audionic-airbud-550-slide",
    name: "Audionic Airbud 550 Slide Earbuds",
    price: 4500,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/AudionicAirbud550SlideEarbuds.webp",
    stock: 10,
    description: "Audionic Airbud 550 Slide with sleek design and clear audio.",
  },
  {
    id: "audionic-airbud-735-ion",
    name: "Audionic Airbud 735 Ion",
    price: 5500,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/735.jpg",
    stock: 8,
    description: "Audionic Airbud 735 Ion with powerful bass and long playtime.",
  },
  {
    id: "audionic-battlebuds-neo",
    name: "Audionic Battlebuds NEO",
    price: 5500,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/neo.jpg",
    stock: 9,
    description: "Audionic Battlebuds NEO built for intense sound and durability.",
  },
  {
    id: "audionic-classic-masti-85",
    name: "Audionic Classic Masti-85",
    price: 5000,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/AudionicClassicMasti-85.jpg",
    stock: 7,
    description: "Audionic Classic Masti-85 with timeless design and rich sound.",
  },
  {
    id: "audionic-coco-c7-mini",
    name: "Audionic COCO C7 Mini",
    price: 2500,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/coco.jpg",
    stock: 15,
    description: "Compact Audionic COCO C7 Mini earbuds for everyday listening.",
  },
  {
    id: "audionic-max-550-bt-plus",
    name: "Audionic MAX 550 BT PLUS",
    price: 12000,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/max230_38a6272e-fbd4-45e9-bffe-200c3039e583.jpg",
    stock: 5,
    description: "Audionic MAX 550 BT PLUS with premium wireless performance.",
  },
  {
    id: "audionic-max-230",
    name: "Audionic Max-230",
    price: 4500,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/max230_fbed2534-97d7-40e1-83e2-33a7d8f2ca8b.jpg",
    stock: 12,
    description: "Audionic Max-230 wireless earbuds with bold sound signature.",
  },
  {
    id: "audionic-pace-7",
    name: "Audionic Pace-7",
    price: 18000,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/download.jpg",
    stock: 4,
    description: "Audionic Pace-7 flagship earbuds with exceptional audio quality.",
  },
  {
    id: "audionic-trance-airbud-810",
    name: "Audionic Trance Airbud 810",
    price: 9000,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/810.jpg",
    stock: 6,
    description: "Audionic Trance Airbud 810 with immersive trance sound profile.",
  },
  {
    id: "audionic-trance-airbud-815",
    name: "Audionic Trance Airbud 815",
    price: 8500,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/download_16.jpg",
    stock: 6,
    description: "Audionic Trance Airbud 815 with enhanced bass and clarity.",
  },
  {
    id: "audionic-trance-airbud-850",
    name: "Audionic Trance Airbud 850",
    price: 10000,
    brand: "Audionic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/850.jpg",
    stock: 5,
    description: "Audionic Trance Airbud 850 flagship with premium wireless audio.",
  },
  {
    id: "samsung-galaxy-buds3",
    name: "Samsung Galaxy Buds3",
    price: 3500,
    brand: "Samsung",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/samsung-galaxy-buds3.jpg",
    stock: 14,
    description: "Samsung Galaxy Buds3 with crisp sound and comfortable fit.",
  },
  {
    id: "earbuds-usb-c-universal",
    name: "Earbuds with USB-C Connector (Universal)",
    price: 800,
    brand: "Generic",
    category: "Earbuds",
    image: "https://alimobilezone.com/cdn/shop/files/apple-copy-earbuds-lightningcopy.jpg",
    stock: 28,
    description: "Universal USB-C earbuds compatible with most modern devices.",
  },

  // ====== Headphones ======
  {
    id: "r-1500-headphone",
    name: "R-1500 Headphone",
    price: 5695,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r1500.jpg",
    stock: 10,
    description: "Over-ear headphones with deep bass and comfortable fit.",
  },
  {
    id: "r-1505-headphone",
    name: "R-1505 Headphone",
    price: 6595,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r1505.jpg",
    stock: 8,
    description: "Premium headphones with clear highs and powerful lows.",
  },
  {
    id: "r-1510-headphone",
    name: "R-1510 Headphone",
    price: 4995,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r1510.webp",
    stock: 12,
    description: "Lightweight headphones with balanced sound for daily use.",
  },
  {
    id: "r-1515-headphone",
    name: "R-1515 Headphone",
    price: 8995,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r1515.webp",
    stock: 6,
    description: "Premium wireless headphones with crystal clear audio.",
  },
  {
    id: "r-1520-headphone",
    name: "R-1520 Headphone",
    price: 6995,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r1520.jpg",
    stock: 7,
    description: "High-performance headphones with immersive soundstage.",
  },
  {
    id: "r-3505-rage",
    name: "R-3505 Rage",
    price: 3795,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r3505.webp",
    stock: 14,
    description: "Rage series with punchy bass for energetic listening.",
  },
  {
    id: "r-3510-cord",
    name: "R-3510 Cord",
    price: 4995,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r3510.jpg",
    stock: 10,
    description: "Wired headphones with premium build and detailed sound.",
  },
  {
    id: "r-190-mashion",
    name: "R-190 Mashion",
    price: 4095,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r190.webp",
    stock: 12,
    description: "Mashion series headphones with stylish design and clear audio.",
  },
  {
    id: "r-520-dynasty",
    name: "R-520 Dynasty",
    price: 5095,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r520.webp",
    stock: 8,
    description: "Dynasty headphones with superior comfort and balanced tone.",
  },
  {
    id: "r-740-vivid",
    name: "R-740 Vivid",
    price: 4095,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/W2_98e6293c-4be5-4c57-8728-5352e8d2f200.webp",
    stock: 11,
    description: "Vivid headphones with lively sound and ergonomic design.",
  },
  {
    id: "r-7010-mystique",
    name: "R-7010 Mystique",
    price: 5395,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7010.webp",
    stock: 8,
    description: "Mystique series headphones with rich audio profile.",
  },
  {
    id: "r-7035-dominator",
    name: "R-7035 Dominator",
    price: 6695,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7035.webp",
    stock: 6,
    description: "Dominator headphones with commanding bass presence.",
  },
  {
    id: "r-7050-eminence",
    name: "R-7050 Eminence",
    price: 5795,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/7050.webp",
    stock: 7,
    description: "Eminence headphones with balanced sound and long battery life.",
  },
  {
    id: "r-7065-eclipse",
    name: "R-7065 Eclipse",
    price: 6695,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7065.webp",
    stock: 6,
    description: "Eclipse headphones offering premium noise isolation.",
  },
  {
    id: "r-7070-snap",
    name: "R-7070 Snap",
    price: 5595,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7070.jpg",
    stock: 9,
    description: "Snap headphones with crisp audio and foldable design.",
  },
  {
    id: "r-7075-vesper",
    name: "R-7075 Vesper",
    price: 5895,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7075.webp",
    stock: 7,
    description: "Vesper headphones with refined sound and elegant finish.",
  },
  {
    id: "r-7080-nox",
    name: "R-7080 NOX",
    price: 5795,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/images_2.jpg",
    stock: 8,
    description: "NOX headphones with dark aesthetic and powerful audio.",
  },
  {
    id: "r-7085-vox",
    name: "R-7085 VOX",
    price: 6395,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7085.webp",
    stock: 6,
    description: "VOX headphones with vocal-tuned sound signature.",
  },
  {
    id: "r-7090-iron-edge",
    name: "R-7090 Iron Edge",
    price: 8096,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7090.jpg",
    stock: 5,
    description: "Iron Edge with rugged build and heavy-duty sound performance.",
  },
  {
    id: "r-7095-reactor-x",
    name: "R-7095 Reactor X",
    price: 7595,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7095.jpg",
    stock: 5,
    description: "Reactor X with explosive sound and premium materials.",
  },
  {
    id: "r-7100-mellow",
    name: "R-7100 Mellow",
    price: 5595,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/7200.webp",
    stock: 8,
    description: "Mellow headphones with smooth audio for relaxed listening.",
  },
  {
    id: "r-7105-warrior",
    name: "R-7105 Warrior",
    price: 5895,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7105.jpg",
    stock: 7,
    description: "Warrior headphones built tough with bold sound output.",
  },
  {
    id: "r-7110-glacier",
    name: "R-7110 Glacier",
    price: 5695,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7110_4c691312-6fc4-430e-b317-c19012bed1f7.jpg",
    stock: 7,
    description: "Glacier headphones with cool design and crisp treble.",
  },
  {
    id: "r-7140-mashion-pro",
    name: "R-7140 Mashion Pro",
    price: 4595,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7140.webp",
    stock: 10,
    description: "Mashion Pro with upgraded drivers for enhanced audio.",
  },
  {
    id: "r-7145-glaze",
    name: "R-7145 Glaze",
    price: 5795,
    brand: "Ronin",
    category: "Headphones",
    image: "https://alimobilezone.com/cdn/shop/files/r7145.jpg",
    stock: 7,
    description: "Glaze headphones with glossy finish and refined acoustics.",
  },

  // ====== Chargers ======
  {
    id: "r-615-charger-android",
    name: "R-615 Charger (Android)",
    price: 1025,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r615_f29b6102-b3c5-42a2-bea8-58e4ea2ec1f8.jpg",
    stock: 25,
    description: "Fast Android charger with durable cable for everyday charging.",
  },
  {
    id: "r-666-charger-android",
    name: "R-666 Charger (Android)",
    price: 815,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r666.jpg",
    stock: 30,
    description: "Compact Android charger built for safe and steady power delivery.",
  },
  {
    id: "r-666-charger-type-c",
    name: "R-666 Charger (Type-C)",
    price: 845,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r666tc.webp",
    stock: 28,
    description: "Type-C charger with stable output for modern smartphones.",
  },
  {
    id: "r-777-charger-android",
    name: "R-777 Charger (Android)",
    price: 795,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r777_ffaa01b0-7510-443f-b3b6-1be6004e087b.webp",
    stock: 40,
    description: "Reliable Android charger at an unbeatable price.",
  },
  {
    id: "r-6020-wizard",
    name: "R-6020 Wizard",
    price: 4295,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r6020_026021a3-d535-480b-83b4-22a5f3fea898.jpg",
    stock: 8,
    description: "Premium fast-charging wizard with multi-port output.",
  },
  {
    id: "r-6025-charger",
    name: "R-6025 Charger",
    price: 1995,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r6025.jpg",
    stock: 15,
    description: "High-output charger for fast and safe charging.",
  },
  {
    id: "r-6030-charger",
    name: "R-6030 Charger",
    price: 2045,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r6030_2000e46d-feae-4969-918e-344a735507fb.jpg",
    stock: 12,
    description: "Premium build charger with fast charging support.",
  },
  {
    id: "r-6035-charger",
    name: "R-6035 Charger",
    price: 2395,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r6035.jpg",
    stock: 10,
    description: "Fast charger with smart protection circuits.",
  },
  {
    id: "r-6040-charger",
    name: "R-6040 Charger",
    price: 8195,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r6040_5b8bff29-1d64-4871-9274-032ea5c23f5a.jpg",
    stock: 5,
    description: "Flagship multi-port charger for power users.",
  },
  {
    id: "r-6045-charger",
    name: "R-6045 Charger",
    price: 2395,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/6045.jpg",
    stock: 12,
    description: "Reliable fast charger with premium feel.",
  },
  {
    id: "r-6050-charger",
    name: "R-6050 Charger",
    price: 1245,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r6050_2a828a8d-e89b-4203-8494-8680439277b4.jpg",
    stock: 22,
    description: "Compact daily-use charger with solid performance.",
  },
  {
    id: "r-6055-charger",
    name: "R-6055 Charger",
    price: 815,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r6055_aec7b502-99a9-4364-bf51-7fe5e5a75130.jpg",
    stock: 35,
    description: "Affordable charger with safe output for any phone.",
  },
  {
    id: "r-6060-charger",
    name: "R-6060 Charger",
    price: 2445,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r6060.jpg",
    stock: 10,
    description: "Premium fast charger with sturdy cable.",
  },
  {
    id: "r-6065-charger",
    name: "R-6065 Charger",
    price: 3995,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r6065.jpg",
    stock: 7,
    description: "High-end charger with rapid charging technology.",
  },
  {
    id: "r-2505-car-charger",
    name: "R-2505 Car Charger",
    price: 1545,
    brand: "Ronin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/r2505_638062bf-58b3-4dd1-a451-cc4bf56a0040.webp",
    stock: 20,
    description: "Dual-port car charger for fast on-the-go power.",
  },
  {
    id: "infinix-charger",
    name: "Infinix Charger",
    price: 1800,
    brand: "Infinix",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/download_e623bf26-6f4f-43ed-939e-423e3687b12d.jpg",
    stock: 18,
    description: "Original Infinix charger with fast charging support.",
  },
  {
    id: "mi-charger",
    name: "Mi Charger",
    price: 3000,
    brand: "Xiaomi",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/download_9c4f446f-f115-4c76-a37a-4e75eff683e0.png",
    stock: 15,
    description: "Original Mi charger with reliable power delivery.",
  },
  {
    id: "oneplus-charger",
    name: "OnePlus Charger",
    price: 3500,
    brand: "OnePlus",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/download_20c02b04-8216-495a-8b77-06709e3a00d3.jpg",
    stock: 12,
    description: "Original OnePlus Warp Charge adapter for fast charging.",
  },
  {
    id: "oppo-supervooc-charger",
    name: "OPPO SuperVOOC Charger",
    price: 6500,
    brand: "OPPO",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/download_016713e6-1dd8-40ad-8b1b-efae0da0afd5.jpg",
    stock: 8,
    description: "OPPO SuperVOOC charger with ultra-fast charging technology.",
  },
  {
    id: "pixel-charger",
    name: "Pixel Charger",
    price: 4000,
    brand: "Google",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/download_bd5f3349-b84b-41fb-8685-b1ac2eeeaf28.jpg",
    stock: 10,
    description: "Original Google Pixel charger with USB-C fast charging.",
  },
  {
    id: "vivo-flash-charger",
    name: "Vivo Flash Charger",
    price: 4000,
    brand: "Vivo",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/download_64f88649-4985-481a-81ec-fecc7f19981e.jpg",
    stock: 10,
    description: "Original Vivo Flash Charge adapter for rapid battery top-up.",
  },
  {
    id: "belkin-boost-charge-wireless-pad",
    name: "Belkin Boost Charge Wireless Pad",
    price: 3000,
    brand: "Belkin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/belkin-boost-charge-wireless-pad.jpg",
    stock: 12,
    description: "Belkin wireless charging pad with fast charge support.",
  },
  {
    id: "apple-magsafe-battery-pack",
    name: "Apple MagSafe Battery Pack",
    price: 6000,
    brand: "Apple",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/vapple-magsafe-battery-pack.webp",
    stock: 8,
    description: "Apple MagSafe battery pack for on-the-go wireless charging.",
  },
  {
    id: "apple-magsafe-charger-usb-c",
    name: "Apple MagSafe Charger (USB-C)",
    price: 2500,
    brand: "Apple",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/apple-magsafe-charger-usbc_1ceaa67a-4439-4035-b5ed-c26db71a2b67.jpg",
    stock: 15,
    description: "Apple MagSafe charger with USB-C for fast wireless charging.",
  },
  {
    id: "apple-magsafe-charger-pad",
    name: "Apple MagSafe Charger (Wireless Pad)",
    price: 2500,
    brand: "Apple",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/apple-magsafe-charger-pad.jpg",
    stock: 15,
    description: "Apple MagSafe wireless charging pad for compatible iPhones.",
  },
  {
    id: "apple-magsafe-duo-charger",
    name: "Apple MagSafe Duo Charger",
    price: 2500,
    brand: "Apple",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/apple-magsafe-duo-charger_df3ea87e-35f3-40b6-b30e-6439d0cd8217.jpg",
    stock: 10,
    description: "Apple MagSafe Duo charger for phone and watch simultaneously.",
  },
  {
    id: "azmuth-magsafe-power-bank-5000",
    name: "Azmuth MagSafe Power Bank 5000 mAh",
    price: 4000,
    brand: "Azmuth",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/azmuth-magsafe-power-bank.jpg",
    stock: 14,
    description: "Azmuth MagSafe power bank with 5000 mAh capacity.",
  },
  {
    id: "ugreen-magflow-magsafe-power-bank",
    name: "UGREEN MagFlow MagSafe Power Bank",
    price: 8000,
    brand: "UGREEN",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/ugreen-magflow-power-bank.jpg",
    stock: 6,
    description: "UGREEN MagFlow power bank with MagSafe magnetic attachment.",
  },
  {
    id: "belkin-usb-c-to-usb-c-cable",
    name: "Belkin USB-C to USB-C Cable",
    price: 800,
    brand: "Belkin",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/belkin-usbc-usbc-cable_65089fdd-74ae-4256-9f50-f32a711ebb2d.jpg",
    stock: 25,
    description: "Belkin USB-C to USB-C cable for fast data sync and charging.",
  },
  {
    id: "apple-usb-c-cable",
    name: "Apple USB-C Cable",
    price: 350,
    brand: "Apple",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/apple-usb-c-cable.jpg",
    stock: 40,
    description: "Official Apple USB-C cable for charging and data transfer.",
  },
  {
    id: "apple-usb-c-to-lightning-cable",
    name: "Apple USB-C to Lightning Cable",
    price: 750,
    brand: "Apple",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/apple-usb-c-to-lightning-cable.jpg",
    stock: 30,
    description: "Apple USB-C to Lightning cable for fast charging your iPhone.",
  },
  {
    id: "apple-usb-c-to-usb-c-cable-braided",
    name: "Apple USB-C to USB-C Cable 1m Braided",
    price: 2500,
    brand: "Apple",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/apple-usbc-usbc-braided.jpg",
    stock: 15,
    description: "Durable braided USB-C to USB-C cable from Apple.",
  },
  {
    id: "mi-cable",
    name: "Mi Cable",
    price: 600,
    brand: "Xiaomi",
    category: "Chargers",
    image: "https://alimobilezone.com/cdn/shop/files/download_3dc0d19b-fb7e-4731-b011-2e2b9a396675.jpg",
    stock: 35,
    description: "Original Mi USB cable for reliable charging and syncing.",
  },

  // ====== Apple Products ======
  {
    id: "apple-lightning-to-3-5mm-adapter",
    name: "Apple Lightning to 3.5mm Headphone Jack Adapter",
    price: 500,
    brand: "Apple",
    category: "Apple Products",
    image: "https://alimobilezone.com/cdn/shop/files/download_e0246238-9c70-4ec7-ac81-26f3c8aa8551.jpg",
    stock: 35,
    description: "Apple Lightning to 3.5mm adapter for wired headphone use.",
  },
  {
    id: "apple-usb-c-to-3-5mm-adapter",
    name: "Apple USB-C to 3.5mm Headphone Jack Adapter",
    price: 400,
    brand: "Apple",
    category: "Apple Products",
    image: "https://alimobilezone.com/cdn/shop/files/apple-usbc-to-3-5mm-adapter.jpg",
    stock: 35,
    description: "Apple USB-C to 3.5mm adapter for modern Mac and iPad.",
  },
  {
    id: "apple-usb-c-to-lightning-adapter",
    name: "Apple USB-C to Lightning Adapter",
    price: 450,
    brand: "Apple",
    category: "Apple Products",
    image: "https://alimobilezone.com/cdn/shop/files/apple-usbc-to-lightning-adapterapple-usbc-to-lightning-adapter.jpg",
    stock: 30,
    description: "Apple USB-C to Lightning adapter for accessory connectivity.",
  },
  {
    id: "mfi-certified-lightning-to-3-5mm",
    name: "MFi Certified Lightning to 3.5mm Adapter (2 Pack)",
    price: 1500,
    brand: "Apple",
    category: "Apple Products",
    image: "https://alimobilezone.com/cdn/shop/files/download_b62c5563-da48-42b7-b6fa-41880854468c.jpg",
    stock: 20,
    description: "MFi certified Lightning to 3.5mm adapter two-pack.",
  },
  {
    id: "ugreen-lightning-to-3-5mm-adapter",
    name: "UGREEN Lightning to 3.5mm Adapter Bluetooth (MFi Certified)",
    price: 400,
    brand: "UGREEN",
    category: "Apple Products",
    image: "https://alimobilezone.com/cdn/shop/files/ugreen-lightning-to-3-5mm.jpg",
    stock: 25,
    description: "UGREEN MFi certified Lightning to 3.5mm audio adapter.",
  },

  // ====== Ronin Products ======
  {
    id: "r-007-handsfree-aux",
    name: "R-007 Handsfree AUX",
    price: 1925,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r007.webp",
    stock: 15,
    description: "Ronin R-007 handsfree earphones with AUX connector.",
  },
  {
    id: "r-007-handsfree-type-c",
    name: "R-007 Handsfree Type-C",
    price: 2095,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r007tc.webp",
    stock: 14,
    description: "Ronin R-007 handsfree earphones with Type-C connector.",
  },
  {
    id: "r-010-luxe",
    name: "R-010 Luxe",
    price: 11295,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r010luxe_0755ac03-0af3-4d9b-b9c6-65fbae7e8d63.jpg",
    stock: 5,
    description: "Ronin R-010 Luxe smart band with premium finish and features.",
  },
  {
    id: "r-010-silicon",
    name: "R-010 Silicon",
    price: 10295,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r010sillicon_2553e8ff-9f93-4641-af16-09f27d3a5cde.jpg",
    stock: 6,
    description: "Ronin R-010 Silicon smart band with comfortable silicone strap.",
  },
  {
    id: "r-013-luxe",
    name: "R-013 Luxe",
    price: 7895,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r013luxe.jpg",
    stock: 7,
    description: "Ronin R-013 Luxe smartwatch with premium build.",
  },
  {
    id: "r-013-rugged",
    name: "R-013 Rugged",
    price: 7395,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/images_1.jpg",
    stock: 8,
    description: "Ronin R-013 Rugged smartwatch built for outdoor use.",
  },
  {
    id: "r-014-luxe",
    name: "R-014 Luxe",
    price: 9995,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r014luxe.jpg",
    stock: 6,
    description: "Ronin R-014 Luxe smartwatch with elegant design.",
  },
  {
    id: "r-09-luxe",
    name: "R-09 Luxe",
    price: 11095,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r09luxe_f6f22ecd-f154-4992-bd86-1b1f13552036.webp",
    stock: 6,
    description: "Ronin R-09 Luxe smartwatch with premium features.",
  },
  {
    id: "r-09-silicon",
    name: "R-09 Silicon",
    price: 10195,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/R-09SmartWatchnickel1_a236a84e-0495-4a06-a2a7-c5348d4904aa.webp",
    stock: 7,
    description: "Ronin R-09 Silicon smartwatch with comfortable silicone band.",
  },
  {
    id: "r-09-ultra",
    name: "R-09 Ultra",
    price: 10595,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r09ulta.webp",
    stock: 5,
    description: "Ronin R-09 Ultra flagship smartwatch with advanced tracking.",
  },
  {
    id: "r-15-handsfree-aux",
    name: "R-15 Handsfree AUX",
    price: 795,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r15.jpg",
    stock: 22,
    description: "Ronin R-15 handsfree earphones with 3.5mm AUX jack.",
  },
  {
    id: "r-27-handsfree-type-c",
    name: "R-27 Handsfree Type-C",
    price: 1445,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r27.webp",
    stock: 16,
    description: "Ronin R-27 handsfree earphones with Type-C connector.",
  },
  {
    id: "r-29-handsfree-aux",
    name: "R-29 Handsfree AUX",
    price: 785,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r29.webp",
    stock: 24,
    description: "Ronin R-29 handsfree earphones with 3.5mm AUX jack.",
  },
  {
    id: "r-29-handsfree-type-c",
    name: "R-29 Handsfree Type-C",
    price: 1175,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r29tc.jpg",
    stock: 20,
    description: "Ronin R-29 handsfree earphones with Type-C connector.",
  },
  {
    id: "r-5-handsfree-aux",
    name: "R-5 Handsfree AUX",
    price: 1355,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r5.webp",
    stock: 18,
    description: "Ronin R-5 handsfree earphones with 3.5mm AUX connector.",
  },
  {
    id: "r-5-handsfree-type-c",
    name: "R-5 Handsfree Type-C",
    price: 1495,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r5tc.webp",
    stock: 16,
    description: "Ronin R-5 handsfree earphones with Type-C connector.",
  },
  {
    id: "r-825-iphone-bluetooth",
    name: "R-825 iPhone (Bluetooth)",
    price: 1975,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r825.jpg",
    stock: 12,
    description: "Ronin R-825 Bluetooth earphones designed for iPhone.",
  },
  {
    id: "r-825-iphone-plug-play",
    name: "R-825 Plug and Play iPhone",
    price: 1975,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r825_e1a7b81f-94f7-4f02-9f31-99158d56781c.jpg",
    stock: 12,
    description: "Ronin R-825 plug and play earphones for iPhone.",
  },
  {
    id: "r-9-handsfree-aux",
    name: "R-9 Handsfree AUX",
    price: 885,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r9.webp",
    stock: 24,
    description: "Ronin R-9 handsfree earphones with 3.5mm AUX jack.",
  },
  {
    id: "r-9-handsfree-type-c",
    name: "R-9 Handsfree Type-C",
    price: 1305,
    brand: "Ronin",
    category: "Ronin Products",
    image: "https://alimobilezone.com/cdn/shop/files/r9tc.webp",
    stock: 20,
    description: "Ronin R-9 handsfree earphones with Type-C connector.",
  },

  // ====== Accessories ======
  {
    id: "bluetooth-5-0-audio-receiver",
    name: "Bluetooth 5.0 Audio Receiver Adapter 3.5mm",
    price: 700,
    brand: "Generic",
    category: "Accessories",
    image: "https://alimobilezone.com/cdn/shop/files/download_7d53c4df-153b-4f51-9f34-abe7fbb370c4.jpg",
    stock: 30,
    description: "Bluetooth 5.0 audio receiver with 3.5mm output for wired devices.",
  },
  {
    id: "usb-c-to-3-5mm-audio-adapter-hifi",
    name: "USB-C to 3.5mm Audio Adapter HiFi (2 Pack)",
    price: 700,
    brand: "Generic",
    category: "Accessories",
    image: "https://alimobilezone.com/cdn/shop/files/usbc-to-3-5mm-adapter-hifi.jpg",
    stock: 30,
    description: "HiFi USB-C to 3.5mm audio adapter two-pack for clear sound.",
  },

  // ====== New Additions - Chargers ======
  {
    id: "20w-pd-charger",
    name: "20W PD Charger",
    price: 1500,
    brand: "Generic",
    category: "Chargers",
    image: "https://www.belkin.com/images/products/20w-pd-charger.jpg",
    stock: 25,
    description: "Fast 20W PD charger for quick charging of compatible devices.",
  },
  {
    id: "25w-super-fast-charger",
    name: "25W Super Fast Charger",
    price: 2000,
    brand: "Generic",
    category: "Chargers",
    image: "https://www.belkin.com/images/products/25w-super-fast-charger.jpg",
    stock: 20,
    description: "25W super fast charger for Samsung and compatible devices.",
  },
  {
    id: "33w-fast-charger",
    name: "33W Fast Charger",
    price: 2500,
    brand: "Generic",
    category: "Chargers",
    image: "https://www.reflying.com/cdn/shop/products/33w-gan-charger.jpg",
    stock: 18,
    description: "33W fast charger with rapid charging for smartphones.",
  },
  {
    id: "45w-super-fast-charger",
    name: "45W Super Fast Charger",
    price: 3500,
    brand: "Generic",
    category: "Chargers",
    image: "https://myhypergear.com/cdn/shop/products/45w-gan-charger.jpg",
    stock: 15,
    description: "45W super fast charger for ultra-fast charging experience.",
  },
  {
    id: "65w-gan-charger",
    name: "65W GaN Charger",
    price: 5000,
    brand: "Generic",
    category: "Chargers",
    image: "https://in.store.asus.com/media/catalog/product/65w-gan-charger.jpg",
    stock: 10,
    description: "65W GaN charger compact and powerful for laptops and phones.",
  },
  {
    id: "usb-wall-charger",
    name: "USB Wall Charger",
    price: 800,
    brand: "Generic",
    category: "Chargers",
    image: "https://www.belkin.com/images/products/usb-wall-charger.jpg",
    stock: 35,
    description: "Standard USB wall charger for everyday charging needs.",
  },
  {
    id: "dual-usb-charger",
    name: "Dual USB Charger",
    price: 1000,
    brand: "Generic",
    category: "Chargers",
    image: "https://www.belkin.com/images/products/dual-usb-charger.jpg",
    stock: 30,
    description: "Dual USB charger for charging two devices simultaneously.",
  },
  {
    id: "type-c-charger",
    name: "Type-C Charger",
    price: 1200,
    brand: "Generic",
    category: "Chargers",
    image: "https://www.belkin.com/images/products/type-c-charger.jpg",
    stock: 28,
    description: "Type-C charger with fast charging for modern devices.",
  },
  {
    id: "lightning-charger",
    name: "Lightning Charger",
    price: 1200,
    brand: "Generic",
    category: "Chargers",
    image: "https://www.belkin.com/images/products/lightning-charger.jpg",
    stock: 28,
    description: "Lightning connector charger for Apple devices.",
  },
  {
    id: "micro-usb-charger",
    name: "Micro USB Charger",
    price: 800,
    brand: "Generic",
    category: "Chargers",
    image: "https://www.belkin.com/images/products/micro-usb-charger.jpg",
    stock: 35,
    description: "Micro USB charger for older Android and accessory devices.",
  },
  {
    id: "wireless-charger",
    name: "Wireless Charger",
    price: 2000,
    brand: "Generic",
    category: "Chargers",
    image: "https://www.belkin.com/images/products/wireless-charger.jpg",
    stock: 20,
    description: "Qi-compatible wireless charger for cable-free charging.",
  },
  {
    id: "magsafe-charger",
    name: "MagSafe Charger",
    price: 3000,
    brand: "Generic",
    category: "Chargers",
    image: "https://www.belkin.com/images/products/magsafe-charger.jpg",
    stock: 15,
    description: "MagSafe compatible charger with magnetic alignment.",
  },

  // ====== Data Cables ======
  {
    id: "usb-c-to-usb-c-cable",
    name: "USB-C to USB-C Cable",
    price: 600,
    brand: "Generic",
    category: "Data Cables",
    image: "https://www.belkin.com/images/products/usb-c-to-usb-c-cable.jpg",
    stock: 40,
    description: "USB-C to USB-C cable for data sync and charging.",
  },
  {
    id: "usb-a-to-usb-c-cable",
    name: "USB-A to USB-C Cable",
    price: 500,
    brand: "Generic",
    category: "Data Cables",
    image: "https://www.apple.com/shop/product/mophie-usb-a-to-usb-c-cable.jpg",
    stock: 45,
    description: "USB-A to USB-C cable for connecting older chargers to new devices.",
  },
  {
    id: "usb-a-to-lightning-cable",
    name: "USB-A to Lightning Cable",
    price: 700,
    brand: "Generic",
    category: "Data Cables",
    image: "https://www.belkin.com/images/products/usb-a-to-lightning-cable.jpg",
    stock: 35,
    description: "USB-A to Lightning cable for iPhone and iPad charging.",
  },
  {
    id: "usb-c-to-lightning-cable",
    name: "USB-C to Lightning Cable",
    price: 800,
    brand: "Generic",
    category: "Data Cables",
    image: "https://www.belkin.com/images/products/usb-c-to-lightning-cable.jpg",
    stock: 30,
    description: "USB-C to Lightning cable for fast iPhone charging.",
  },
  {
    id: "micro-usb-cable",
    name: "Micro USB Cable",
    price: 350,
    brand: "Generic",
    category: "Data Cables",
    image: "https://www.belkin.com/images/products/micro-usb-cable.jpg",
    stock: 50,
    description: "Micro USB cable for older devices and accessories.",
  },
  {
    id: "3-in-1-charging-cable",
    name: "3-in-1 Charging Cable",
    price: 800,
    brand: "Generic",
    category: "Data Cables",
    image: "https://www.belkin.com/images/products/3-in-1-charging-cable.jpg",
    stock: 25,
    description: "3-in-1 cable with Lightning, USB-C, and Micro USB connectors.",
  },
  {
    id: "magnetic-charging-cable",
    name: "Magnetic Charging Cable",
    price: 1000,
    brand: "Generic",
    category: "Data Cables",
    image: "https://charbycharge.com/store/wp-content/uploads/2022/03/magnetic-charging-cable.jpg",
    stock: 20,
    description: "Magnetic charging cable with detachable tip for easy connection.",
  },
  {
    id: "braided-fast-charging-cable",
    name: "Braided Fast Charging Cable",
    price: 700,
    brand: "Generic",
    category: "Data Cables",
    image: "https://www.belkin.com/images/products/braided-cable.jpg",
    stock: 30,
    description: "Durable braided cable with fast charging support.",
  },

  // ====== Power Banks ======
  {
    id: "10000mah-power-bank",
    name: "10,000mAh Power Bank",
    price: 2500,
    brand: "Generic",
    category: "Power Banks",
    image: "https://us.ugreen.com/cdn/shop/products/10000mah-power-bank.jpg",
    stock: 20,
    description: "10,000mAh portable power bank for all-day charging.",
  },
  {
    id: "20000mah-power-bank",
    name: "20,000mAh Power Bank",
    price: 4000,
    brand: "Generic",
    category: "Power Banks",
    image: "https://www.baseus.com/cdn/shop/products/20000mah-power-bank.jpg",
    stock: 15,
    description: "20,000mAh high-capacity power bank for multiple charges.",
  },
  {
    id: "magsafe-power-bank",
    name: "MagSafe Power Bank",
    price: 3500,
    brand: "Generic",
    category: "Power Banks",
    image: "https://www.baseus.com/cdn/shop/products/magsafe-power-bank.jpg",
    stock: 12,
    description: "MagSafe power bank with magnetic wireless charging.",
  },
  {
    id: "mini-power-bank",
    name: "Mini Power Bank",
    price: 1500,
    brand: "Generic",
    category: "Power Banks",
    image: "https://www.baseus.com/cdn/shop/products/mini-power-bank.jpg",
    stock: 25,
    description: "Compact mini power bank for on-the-go charging.",
  },
  {
    id: "fast-charging-power-bank",
    name: "Fast Charging Power Bank",
    price: 3000,
    brand: "Generic",
    category: "Power Banks",
    image: "https://ambraneindia.com/cdn/shop/products/fast-charging-power-bank.jpg",
    stock: 18,
    description: "Fast charging power bank with quick output for devices.",
  },

  // ====== Earbuds ======
  {
    id: "airpods-pro",
    name: "AirPods Pro",
    price: 2500,
    brand: "Apple",
    category: "Earbuds",
    image: "https://www.apple.com/shop/product/airpods-pro.jpg",
    stock: 20,
    description: "AirPods Pro with active noise cancellation and comfortable fit.",
  },
  {
    id: "galaxy-buds",
    name: "Galaxy Buds",
    price: 3000,
    brand: "Samsung",
    category: "Earbuds",
    image: "https://www.samsung.com/images/products/galaxy-buds.jpg",
    stock: 18,
    description: "Samsung Galaxy Buds with rich sound and ergonomic design.",
  },
  {
    id: "redmi-buds",
    name: "Redmi Buds",
    price: 2500,
    brand: "Xiaomi",
    category: "Earbuds",
    image: "https://www.mi.com/images/products/redmi-buds.jpg",
    stock: 22,
    description: "Redmi wireless earbuds with great value and sound quality.",
  },
  {
    id: "xiaomi-buds",
    name: "Xiaomi Buds",
    price: 3000,
    brand: "Xiaomi",
    category: "Earbuds",
    image: "https://i02.appmifile.com/mi-com-product/fly-birds/pc/xiaomi-buds-4-pro/d018241addeb10b8963cccc3056c3341.jpg",
    stock: 18,
    description: "Xiaomi Buds with premium audio and long battery life.",
  },
  {
    id: "oneplus-buds",
    name: "OnePlus Buds",
    price: 3500,
    brand: "OnePlus",
    category: "Earbuds",
    image: "https://www.oneplus.com/images/products/oneplus-buds.jpg",
    stock: 15,
    description: "OnePlus Buds with seamless connectivity and clear sound.",
  },
  {
    id: "realme-buds-air",
    name: "Realme Buds Air",
    price: 3000,
    brand: "Realme",
    category: "Earbuds",
    image: "https://www.realme.com/in/realme-buds-air.jpg",
    stock: 16,
    description: "Realme Buds Air with stylish design and immersive audio.",
  },
  {
    id: "m10-tws-earbuds",
    name: "M10 TWS Earbuds",
    price: 1500,
    brand: "Generic",
    category: "Earbuds",
    image: "https://www.lightinthebox.com/images/products/m10-tws-earbuds.jpg",
    stock: 30,
    description: "Affordable M10 TWS earbuds with compact charging case.",
  },
  {
    id: "m19-tws-earbuds",
    name: "M19 TWS Earbuds",
    price: 1800,
    brand: "Generic",
    category: "Earbuds",
    image: "https://www.lightinthebox.com/images/products/m19-tws-earbuds.jpg",
    stock: 28,
    description: "M19 TWS earbuds with stable connection and good bass.",
  },
  {
    id: "f9-tws-earbuds",
    name: "F9 TWS Earbuds",
    price: 1200,
    brand: "Generic",
    category: "Earbuds",
    image: "https://www.lightinthebox.com/images/products/f9-tws-earbuds.jpg",
    stock: 35,
    description: "Budget-friendly F9 TWS earbuds for everyday listening.",
  },
  {
    id: "lenovo-lp40",
    name: "Lenovo LP40",
    price: 2000,
    brand: "Lenovo",
    category: "Earbuds",
    image: "https://litb-cgis.rightinthebox.com/images/640x640/202405/bps/product/inc/uqrhsc1714627090824.jpg",
    stock: 20,
    description: "Lenovo LP40 earbuds with comfortable in-ear design.",
  },
  {
    id: "lenovo-lp75",
    name: "Lenovo LP75",
    price: 2500,
    brand: "Lenovo",
    category: "Earbuds",
    image: "https://www.ebay.com/images/products/lenovo-lp75.jpg",
    stock: 18,
    description: "Lenovo LP75 earbuds with enhanced audio performance.",
  },
  {
    id: "a9-pro-earbuds",
    name: "A9 Pro Earbuds",
    price: 2500,
    brand: "Generic",
    category: "Earbuds",
    image: "https://www.lightinthebox.com/images/products/a9-pro-earbuds.jpg",
    stock: 20,
    description: "A9 Pro TWS earbuds with premium features and sound.",
  },

  // ====== Headphones ======
  {
    id: "p9-wireless-headphones",
    name: "P9 Wireless Headphones",
    price: 2500,
    brand: "Generic",
    category: "Headphones",
    image: "https://www.daraz.pk/images/products/p9-headphones.jpg",
    stock: 15,
    description: "P9 wireless headphones with comfortable over-ear design.",
  },
  {
    id: "p47-wireless-headphones",
    name: "P47 Wireless Headphones",
    price: 3000,
    brand: "Generic",
    category: "Headphones",
    image: "https://www.walmart.com/images/products/p47-headphones.jpg",
    stock: 12,
    description: "P47 wireless headphones with deep bass and long battery.",
  },
  {
    id: "jbl-style-headphones",
    name: "JBL Style Headphones",
    price: 4000,
    brand: "Generic",
    category: "Headphones",
    image: "https://www.jbl.com/images/products/jbl-headphones.jpg",
    stock: 10,
    description: "JBL-inspired style headphones with signature sound.",
  },
  {
    id: "sony-style-headphones",
    name: "Sony Style Headphones",
    price: 4500,
    brand: "Generic",
    category: "Headphones",
    image: "https://electronics.sony.com/images/products/sony-headphones.jpg",
    stock: 8,
    description: "Sony-style headphones with premium audio quality.",
  },
  {
    id: "gaming-headset",
    name: "Gaming Headset",
    price: 3500,
    brand: "Generic",
    category: "Headphones",
    image: "https://www.sony.co.uk/images/products/gaming-headset.jpg",
    stock: 12,
    description: "Gaming headset with built-in microphone and surround sound.",
  },
  {
    id: "bluetooth-headphones",
    name: "Bluetooth Headphones",
    price: 2000,
    brand: "Generic",
    category: "Headphones",
    image: "https://www.jbl.com/images/products/bluetooth-headphones.jpg",
    stock: 20,
    description: "Wireless Bluetooth headphones for music and calls.",
  },
  {
    id: "wired-headphones",
    name: "Wired Headphones",
    price: 1500,
    brand: "Generic",
    category: "Headphones",
    image: "https://www.jbl.com/images/products/wired-headphones.jpg",
    stock: 25,
    description: "Classic wired headphones with reliable audio performance.",
  },

  // ====== Smart Watches ======
  {
    id: "hk-series-smart-watch",
    name: "HK Series Smart Watch",
    price: 3000,
    brand: "HK",
    category: "Smart Watches",
    image: "https://www.alibaba.com/images/products/hk-series-watch.jpg",
    stock: 15,
    description: "HK Series smart watch with fitness tracking and notifications.",
  },
  {
    id: "t800-ultra",
    name: "T800 Ultra",
    price: 4000,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://www.flipkart.com/images/products/t800-ultra.jpg",
    stock: 12,
    description: "T800 Ultra smart watch with premium design and features.",
  },
  {
    id: "t900-ultra",
    name: "T900 Ultra",
    price: 4500,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://www.flipkart.com/images/products/t900-ultra.jpg",
    stock: 10,
    description: "T900 Ultra smart watch with advanced health monitoring.",
  },
  {
    id: "t1000-ultra",
    name: "T1000 Ultra",
    price: 5000,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://cdn.allware.com/images/3b6ddff9-9fa9-4252-8f64-fd4de22ff2b0?width=3840&format=webp",
    stock: 8,
    description: "T1000 Ultra flagship smart watch with comprehensive features.",
  },
  {
    id: "w26-plus",
    name: "W26 Plus",
    price: 2500,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://www.flipkart.com/images/products/w26-plus.jpg",
    stock: 20,
    description: "W26 Plus smart watch with essential fitness tracking.",
  },
  {
    id: "w29-ultra",
    name: "W29 Ultra",
    price: 3500,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://www.flipkart.com/images/products/w29-ultra.jpg",
    stock: 14,
    description: "W29 Ultra smart watch with sporty design and features.",
  },
  {
    id: "w59-ultra",
    name: "W59 Ultra",
    price: 3800,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://www.flipkart.com/images/products/w59-ultra.jpg",
    stock: 12,
    description: "W59 Ultra smart watch with rugged build and health tracking.",
  },
  {
    id: "s8-ultra",
    name: "S8 Ultra",
    price: 3500,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://www.flipkart.com/images/products/s8-ultra.jpg",
    stock: 15,
    description: "S8 Ultra smart watch with sleek design and smart features.",
  },
  {
    id: "s9-ultra",
    name: "S9 Ultra",
    price: 4000,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://easygetway.com/dx-images/products/s9-ultra-49mm-3-straps-smart-watch-series-9.jpg",
    stock: 12,
    description: "S9 Ultra smart watch with premium finish and functionality.",
  },
  {
    id: "watch-8-ultra",
    name: "Watch 8 Ultra",
    price: 3500,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://www.flipkart.com/images/products/watch-8-ultra.jpg",
    stock: 14,
    description: "Watch 8 Ultra with durable build and activity tracking.",
  },
  {
    id: "watch-9-ultra",
    name: "Watch 9 Ultra",
    price: 4000,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://www.flipkart.com/images/products/watch-9-ultra.jpg",
    stock: 10,
    description: "Watch 9 Ultra with advanced sensors and stylish look.",
  },
  {
    id: "apple-watch-series-clone",
    name: "Apple Watch Series Clone",
    price: 5000,
    brand: "Generic",
    category: "Smart Watches",
    image: "https://www.dhgate.com/images/products/apple-watch-clone.jpg",
    stock: 8,
    description: "Apple Watch style clone with similar design and features.",
  },

  // ====== Phone Cases ======
  {
    id: "silicone-case",
    name: "Silicone Case",
    price: 500,
    brand: "Generic",
    category: "Phone Cases",
    image: "https://armorcase.us/images/products/silicone-case.jpg",
    stock: 40,
    description: "Soft silicone case for everyday protection.",
  },
  {
    id: "transparent-case",
    name: "Transparent Case",
    price: 400,
    brand: "Generic",
    category: "Phone Cases",
    image: "https://afcase.com/images/products/transparent-case.jpg",
    stock: 45,
    description: "Clear transparent case that shows your phone's design.",
  },
  {
    id: "matte-case",
    name: "Matte Case",
    price: 600,
    brand: "Generic",
    category: "Phone Cases",
    image: "https://styleeo.com/images/products/matte-case.jpg",
    stock: 35,
    description: "Matte finish case with anti-fingerprint coating.",
  },
  {
    id: "leather-case",
    name: "Leather Case",
    price: 800,
    brand: "Generic",
    category: "Phone Cases",
    image: "https://www.otterbox.com/images/products/leather-case.jpg",
    stock: 25,
    description: "Premium leather case with elegant look and feel.",
  },
  {
    id: "armor-case",
    name: "Armor Case",
    price: 700,
    brand: "Generic",
    category: "Phone Cases",
    image: "https://afcase.com/images/products/armor-case.jpg",
    stock: 30,
    description: "Heavy-duty armor case for maximum drop protection.",
  },
  {
    id: "magnetic-case",
    name: "Magnetic Case",
    price: 800,
    brand: "Generic",
    category: "Phone Cases",
    image: "https://lekcase.com/images/products/magnetic-case.jpg",
    stock: 28,
    description: "Magnetic case compatible with car mounts and accessories.",
  },
  {
    id: "magsafe-case",
    name: "MagSafe Case",
    price: 1000,
    brand: "Generic",
    category: "Phone Cases",
    image: "https://armorcase.us/images/products/magsafe-case.jpg",
    stock: 22,
    description: "MagSafe compatible case with built-in magnets.",
  },
  {
    id: "camera-protection-case",
    name: "Camera Protection Case",
    price: 700,
    brand: "Generic",
    category: "Phone Cases",
    image: "https://lekcase.com/images/products/camera-protection-case.jpg",
    stock: 25,
    description: "Case with raised camera bump protection.",
  },
  {
    id: "glitter-case",
    name: "Glitter Case",
    price: 500,
    brand: "Generic",
    category: "Phone Cases",
    image: "https://www.dhgate.com/images/products/glitter-case.jpg",
    stock: 35,
    description: "Glitter case with sparkling design for a stylish look.",
  },
  {
    id: "carbon-fiber-case",
    name: "Carbon Fiber Case",
    price: 1000,
    brand: "Generic",
    category: "Phone Cases",
    image: "https://lekcase.com/images/products/carbon-fiber-case.jpg",
    stock: 20,
    description: "Carbon fiber case with sporty texture and strong protection.",
  },

  // ====== Screen Protection ======
  {
    id: "9d-tempered-glass",
    name: "9D Tempered Glass",
    price: 500,
    brand: "Generic",
    category: "Screen Protection",
    image: "https://maxpurecases.com/images/products/9d-tempered-glass.jpg",
    stock: 50,
    description: "9D tempered glass screen protector with edge-to-edge coverage.",
  },
  {
    id: "privacy-glass",
    name: "Privacy Glass",
    price: 700,
    brand: "Generic",
    category: "Screen Protection",
    image: "https://www.spigen.com/images/products/privacy-glass.jpg",
    stock: 30,
    description: "Privacy glass protector that keeps your screen private.",
  },
  {
    id: "matte-screen-protector",
    name: "Matte Screen Protector",
    price: 600,
    brand: "Generic",
    category: "Screen Protection",
    image: "https://www.techmatte.com/images/products/matte-screen-protector.jpg",
    stock: 35,
    description: "Matte screen protector reducing glare and fingerprints.",
  },
  {
    id: "hydrogel-film",
    name: "Hydrogel Film",
    price: 400,
    brand: "Generic",
    category: "Screen Protection",
    image: "https://www.ellisedge.net/images/products/hydrogel-film.jpg",
    stock: 40,
    description: "Self-healing hydrogel film for scratch protection.",
  },
  {
    id: "camera-lens-protector",
    name: "Camera Lens Protector",
    price: 300,
    brand: "Generic",
    category: "Screen Protection",
    image: "https://cdn.allware.com/images/e502f287-229e-458d-bbb3-bcc493c6a9f0?width=3840&format=webp",
    stock: 45,
    description: "Camera lens protector to keep your lenses scratch-free.",
  },

  // ====== Car Accessories ======
  {
    id: "car-phone-holder",
    name: "Car Phone Holder",
    price: 800,
    brand: "Generic",
    category: "Car Accessories",
    image: "https://nowraelectronics.com.au/images/products/car-phone-holder.jpg",
    stock: 25,
    description: "Car phone holder for hands-free navigation and calls.",
  },
  {
    id: "magnetic-car-mount",
    name: "Magnetic Car Mount",
    price: 600,
    brand: "Generic",
    category: "Car Accessories",
    image: "https://nowraelectronics.com.au/images/products/magnetic-car-mount.jpg",
    stock: 30,
    description: "Magnetic car mount for easy phone attachment in vehicle.",
  },
  {
    id: "bluetooth-fm-transmitter",
    name: "Bluetooth FM Transmitter",
    price: 1500,
    brand: "Generic",
    category: "Car Accessories",
    image: "https://rexing.com/images/products/bluetooth-fm-transmitter.jpg",
    stock: 18,
    description: "Bluetooth FM transmitter for wireless music in your car.",
  },

  // ====== Audio ======
  {
    id: "bluetooth-speaker",
    name: "Bluetooth Speaker",
    price: 2500,
    brand: "Generic",
    category: "Audio",
    image: "https://www.bose.com/images/products/bluetooth-speaker.jpg",
    stock: 15,
    description: "Portable Bluetooth speaker with rich sound quality.",
  },
  {
    id: "mini-bluetooth-speaker",
    name: "Mini Bluetooth Speaker",
    price: 1500,
    brand: "Generic",
    category: "Audio",
    image: "https://www.mi.com/images/products/mini-bluetooth-speaker.jpg",
    stock: 22,
    description: "Compact mini Bluetooth speaker for on-the-go music.",
  },
  {
    id: "aux-cable",
    name: "AUX Cable",
    price: 300,
    brand: "Generic",
    category: "Audio",
    image: "https://www.belkin.com/images/products/aux-cable.jpg",
    stock: 40,
    description: "3.5mm AUX cable for audio connectivity.",
  },
  {
    id: "audio-splitter",
    name: "Audio Splitter",
    price: 250,
    brand: "Generic",
    category: "Audio",
    image: "https://www.belkin.com/images/products/audio-splitter.jpg",
    stock: 35,
    description: "Audio splitter for sharing music with two headphones.",
  },

  // ====== Storage ======
  {
    id: "usb-flash-drive",
    name: "USB Flash Drive",
    price: 1000,
    brand: "Generic",
    category: "Storage",
    image: "https://www.banggood.com/images/products/usb-flash-drive.jpg",
    stock: 30,
    description: "USB flash drive for portable data storage.",
  },
  {
    id: "otg-adapter",
    name: "OTG Adapter",
    price: 300,
    brand: "Generic",
    category: "Storage",
    image: "https://www.banggood.com/images/products/otg-adapter.jpg",
    stock: 35,
    description: "OTG adapter for connecting USB devices to your phone.",
  },
  {
    id: "memory-card",
    name: "Memory Card",
    price: 1500,
    brand: "Generic",
    category: "Storage",
    image: "https://www.banggood.com/images/products/memory-card.jpg",
    stock: 25,
    description: "High-speed memory card for expanded storage.",
  },
  {
    id: "card-reader",
    name: "Card Reader",
    price: 500,
    brand: "Generic",
    category: "Storage",
    image: "https://www.newegg.com/images/products/card-reader.jpg",
    stock: 28,
    description: "USB card reader for accessing memory cards.",
  },

  // ====== Other Accessories ======
  {
    id: "selfie-stick",
    name: "Selfie Stick",
    price: 500,
    brand: "Generic",
    category: "Accessories",
    image: "https://www.xmwus.com/images/products/selfie-stick.jpg",
    stock: 35,
    description: "Extendable selfie stick for perfect group photos.",
  },
  {
    id: "mobile-tripod",
    name: "Mobile Tripod",
    price: 1000,
    brand: "Generic",
    category: "Accessories",
    image: "https://www.kentfaith.com/images/products/mobile-tripod.jpg",
    stock: 20,
    description: "Sturdy mobile tripod for stable photos and videos.",
  },
  {
    id: "ring-light",
    name: "Ring Light",
    price: 1500,
    brand: "Generic",
    category: "Accessories",
    image: "https://multitasky.com/images/products/ring-light.jpg",
    stock: 15,
    description: "LED ring light for perfect lighting in photos and videos.",
  },
  {
    id: "mobile-cooling-fan",
    name: "Mobile Cooling Fan",
    price: 800,
    brand: "Generic",
    category: "Accessories",
    image: "https://mobeeta.com/images/products/mobile-cooling-fan.jpg",
    stock: 22,
    description: "Phone cooling fan to prevent overheating during gaming.",
  },
  {
    id: "finger-sleeves",
    name: "Finger Sleeves",
    price: 200,
    brand: "Generic",
    category: "Accessories",
    image: "https://www.amazon.com/images/products/finger-sleeves.jpg",
    stock: 50,
    description: "Gaming finger sleeves for smooth touchscreen control.",
  },
  {
    id: "phone-stand",
    name: "Phone Stand",
    price: 400,
    brand: "Generic",
    category: "Accessories",
    image: "https://www.belkin.com/images/products/phone-stand.jpg",
    stock: 40,
    description: "Adjustable phone stand for hands-free viewing.",
  },
  {
    id: "pop-socket",
    name: "Pop Socket",
    price: 300,
    brand: "Generic",
    category: "Accessories",
    image: "https://www.popsockets.com/images/products/pop-socket.jpg",
    stock: 45,
    description: "Pop socket grip for secure phone holding.",
  },
  {
    id: "sim-ejector-pin",
    name: "SIM Ejector Pin",
    price: 100,
    brand: "Generic",
    category: "Accessories",
    image: "https://mobeeta.com/images/products/sim-ejector-pin.jpg",
    stock: 60,
    description: "SIM ejector pin for swapping SIM cards easily.",
  },
  {
    id: "sim-adapter",
    name: "SIM Adapter",
    price: 150,
    brand: "Generic",
    category: "Accessories",
    image: "https://www.amazon.com/images/products/sim-adapter.jpg",
    stock: 55,
    description: "SIM card adapter kit for all SIM sizes.",
  },
  {
    id: "cleaning-kit",
    name: "Cleaning Kit",
    price: 400,
    brand: "Generic",
    category: "Accessories",
    image: "https://www.newegg.com/images/products/cleaning-kit.jpg",
    stock: 35,
    description: "Phone cleaning kit with spray and microfiber cloth.",
  },
  {
    id: "cable-protector",
    name: "Cable Protector",
    price: 200,
    brand: "Generic",
    category: "Accessories",
    image: "https://mobeeta.com/images/products/cable-protector.jpg",
    stock: 50,
    description: "Silicone cable protector to prevent fraying and damage.",
  },
];

export const BEST_SELLER_IDS = new Set([
  "air-buds",
  "anker-soundcore-r50i",
  "apple-airpods-4",
  "apple-airpods-pro-3",
  "r-615-charger-android",
  "r-777-charger-android",
  "r-1515-headphone",
  "r-09-luxe",
  "r-010-luxe",
  "samsung-galaxy-buds3",
  "apple-magsafe-battery-pack",
]);

export const NEW_IDS = new Set([
  "apple-airpods-4",
  "apple-airpods-pro-3",
  "audionic-coco-c7-mini",
  "audionic-trance-airbud-850",
  "r-09-ultra",
  "r-6065-charger",
  "r-7145-glaze",
  "ugreen-magflow-magsafe-power-bank",
  "r-7095-reactor-x",
  "r-7085-vox",
]);
